
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "9303:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./php
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'gemini_db'
      MYSQL_USER: 'gemini_user'
      MYSQL_PASSWORD: 'gemini_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9494:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql_data:
